// bunny-fonts.ts
// AUTO-GENERATED by scripts/build-fonts.mjs — do not edit by hand.
// Loaded by editor/src/font-sources.ts; the loader uses priority dispatch so
// only families NOT already in google-fonts.ts are included (Google-overlap
// would be unreachable dead weight in the bundle).

export interface BunnyFont {
  family: string;
  slug: string;
  weights: number[];
  italics: boolean;
  category?: string;
}

export const BUNNY_FONTS: ReadonlyArray<BunnyFont> = [
  { family: "42dot Sans", slug: "42dot-sans", weights: [300,400,500,600,700,800], italics: false, category: "sans-serif" },
  { family: "Arima Madurai", slug: "arima-madurai", weights: [100,200,300,400,500,700,800,900], italics: false, category: "display" },
  { family: "BBH Sans Bartle", slug: "bbh-sans-bartle", weights: [400], italics: false, category: "sans-serif" },
  { family: "BBH Sans Bogle", slug: "bbh-sans-bogle", weights: [400], italics: false, category: "sans-serif" },
  { family: "BBH Sans Hegarty", slug: "bbh-sans-hegarty", weights: [400], italics: false, category: "sans-serif" },
  { family: "Big Shoulders Display", slug: "big-shoulders-display", weights: [100,200,300,400,500,600,700,800,900], italics: false, category: "display" },
  { family: "Big Shoulders Inline Display", slug: "big-shoulders-inline-display", weights: [100,200,300,400,500,600,700,800,900], italics: false, category: "display" },
  { family: "Big Shoulders Inline Text", slug: "big-shoulders-inline-text", weights: [100,200,300,400,500,600,700,800,900], italics: false, category: "display" },
  { family: "Big Shoulders Stencil Display", slug: "big-shoulders-stencil-display", weights: [100,200,300,400,500,600,700,800,900], italics: false, category: "display" },
  { family: "Big Shoulders Stencil Text", slug: "big-shoulders-stencil-text", weights: [100,200,300,400,500,600,700,800,900], italics: false, category: "display" },
  { family: "Big Shoulders Text", slug: "big-shoulders-text", weights: [100,200,300,400,500,600,700,800,900], italics: false, category: "display" },
  { family: "Briem Hand", slug: "briem-hand", weights: [100,200,300,400,500,600,700,800,900], italics: false, category: "handwriting" },
  { family: "Coda Caption", slug: "coda-caption", weights: [800], italics: false, category: "sans-serif" },
  { family: "Finlandica", slug: "finlandica", weights: [400,500,600,700], italics: true, category: "sans-serif" },
  { family: "Fredoka One", slug: "fredoka-one", weights: [400], italics: false, category: "display" },
  { family: "Gentium Book Basic", slug: "gentium-book-basic", weights: [400,700], italics: true, category: "serif" },
  { family: "Kantumruy", slug: "kantumruy", weights: [300,400,700], italics: false, category: "sans-serif" },
  { family: "Material Symbols", slug: "material-symbols", weights: [100,200,300,400,500,600,700], italics: false, category: "monospace" },
  { family: "Merienda One", slug: "merienda-one", weights: [400], italics: false, category: "handwriting" },
  { family: "Montserrat Subrayada", slug: "montserrat-subrayada", weights: [400,700], italics: false, category: "sans-serif" },
  { family: "Noto Sans Phags Pa", slug: "noto-sans-phags-pa", weights: [400], italics: false, category: "sans-serif" },
  { family: "Pushster", slug: "pushster", weights: [400], italics: false, category: "display" },
  { family: "Saira Stencil One", slug: "saira-stencil-one", weights: [400], italics: false, category: "display" },
  { family: "Source Sans Pro", slug: "source-sans-pro", weights: [200,300,400,600,700,900], italics: true, category: "sans-serif" },
  { family: "Source Serif Pro", slug: "source-serif-pro", weights: [200,300,400,600,700,900], italics: true, category: "serif" },
];
