// fontshare-fonts.ts
// AUTO-GENERATED by scripts/build-fonts.mjs — do not edit by hand.
// Loaded by editor/src/font-sources.ts; the loader uses priority dispatch so
// only families NOT already in google-fonts.ts are included (Google-overlap
// would be unreachable dead weight in the bundle).

export interface FontshareFont {
  family: string;
  slug: string;
  weights: number[];
  italics: boolean;
  category?: string;
}

export const FONTSHARE_FONTS: ReadonlyArray<FontshareFont> = [
  { family: "Aktura", slug: "aktura", weights: [400], italics: false, category: "serif,  blackletter, display" },
  { family: "Alpino", slug: "alpino", weights: [0,100,300,400,500,700,900], italics: false, category: "sans" },
  { family: "Amulya", slug: "amulya", weights: [0,300,400,500,700], italics: true, category: "sans" },
  { family: "Array", slug: "array", weights: [400,600,700], italics: false, category: "display" },
  { family: "Author", slug: "author", weights: [0,200,300,400,500,600,700], italics: true, category: "sans" },
  { family: "Bespoke Sans", slug: "bespoke-sans", weights: [0,300,400,500,700,800], italics: true, category: "sans" },
  { family: "Bespoke Serif", slug: "bespoke-serif", weights: [0,300,400,500,700,800], italics: true, category: "serif" },
  { family: "Bespoke Slab", slug: "bespoke-slab", weights: [0,300,400,500,700,800], italics: true, category: "slab" },
  { family: "Bespoke Stencil", slug: "bespoke-stencil", weights: [0,300,400,500,700,800], italics: true, category: "sans" },
  { family: "Bevellier", slug: "bevellier", weights: [0,100,200,300,400,500,600,700,900], italics: true, category: "display" },
  { family: "Bonny", slug: "bonny", weights: [0,100,300,400,500,700], italics: false, category: "serif" },
  { family: "Boska", slug: "boska", weights: [0,200,300,400,500,700,900], italics: true, category: "serif, display" },
  { family: "Boxing", slug: "boxing", weights: [400], italics: false, category: "display" },
  { family: "Britney", slug: "britney", weights: [0,300,400,700,1000], italics: false, category: "script" },
  { family: "Cabinet Grotesk", slug: "cabinet-grotesk", weights: [0,100,200,300,400,500,700,800,900], italics: false, category: "sans" },
  { family: "Chillax", slug: "chillax", weights: [0,200,300,400,500,600,700], italics: false, category: "sans" },
  { family: "Chubbo", slug: "chubbo", weights: [0,200,300,400,500,700], italics: true, category: "display" },
  { family: "Clash Display", slug: "clash-display", weights: [0,200,300,400,500,600,700], italics: false, category: "sans" },
  { family: "Clash Grotesk", slug: "clash-grotesk", weights: [0,200,300,400,500,600,700], italics: false, category: "sans" },
  { family: "Comico", slug: "comico", weights: [400], italics: false, category: "handwritten" },
  { family: "Erode", slug: "erode", weights: [0,300,400,500,600,700], italics: true, category: "serif" },
  { family: "Excon", slug: "excon", weights: [0,100,300,400,500,700,900], italics: false, category: "sans" },
  { family: "Expose", slug: "expose", weights: [0,400,500,700,900], italics: false, category: "sans" },
  { family: "Gambarino", slug: "gambarino", weights: [400], italics: false, category: "serif" },
  { family: "Gambetta", slug: "gambetta", weights: [0,300,400,500,600,700], italics: true, category: "serif" },
  { family: "General Sans", slug: "general-sans", weights: [0,200,300,400,500,600,700], italics: true, category: "sans" },
  { family: "Hoover", slug: "hoover", weights: [0,100,300,400,500,700], italics: false, category: "slab" },
  { family: "Kihim", slug: "kihim", weights: [400], italics: false, category: "display" },
  { family: "Kohinoor Zerone", slug: "kohinoor-zerone", weights: [100,200], italics: false, category: "display" },
  { family: "Kola", slug: "kola", weights: [400], italics: false, category: "display" },
  { family: "Melodrama", slug: "melodrama", weights: [0,300,400,500,600,700], italics: false, category: "sans, display" },
  { family: "Neco", slug: "neco", weights: [0,400,500,700,900], italics: true, category: "serif" },
  { family: "New Title", slug: "new-title", weights: [0,200,300,400,500,700], italics: false, category: "sans, display" },
  { family: "Nippo", slug: "nippo", weights: [0,200,300,400,500,700], italics: false, category: "display" },
  { family: "Pally", slug: "pally", weights: [0,400,500,700], italics: false, category: "sans" },
  { family: "Panchang", slug: "panchang", weights: [0,200,300,400,500,600,700,800], italics: false, category: "sans" },
  { family: "Paquito", slug: "paquito", weights: [0,400,500,700], italics: false, category: "serif, slab" },
  { family: "Pencerio", slug: "pencerio", weights: [50], italics: false, category: "script" },
  { family: "Pilcrow Rounded", slug: "pilcrow-rounded", weights: [0,400,500,600,700,900], italics: false, category: "sans" },
  { family: "Plein", slug: "plein", weights: [0,300,400,500,700,900], italics: true, category: "sans" },
  { family: "Pramukh Rounded", slug: "pramukh-rounded", weights: [0,200,300,350,400,600,700,800,900], italics: true, category: "sans" },
  { family: "Quilon", slug: "quilon", weights: [0,400,500,600,700], italics: false, category: "sans" },
  { family: "Ranade", slug: "ranade", weights: [0,100,300,400,500,700], italics: true, category: "sans" },
  { family: "Recia", slug: "recia", weights: [0,300,400,500,600,700], italics: true, category: "serif" },
  { family: "Rosaline", slug: "rosaline", weights: [400], italics: false, category: "script" },
  { family: "Roundo", slug: "roundo", weights: [0,200,300,400,500,600,700], italics: false, category: "sans" },
  { family: "Rowan", slug: "rowan", weights: [0,300,400,500,600,700], italics: true, category: "serif" },
  { family: "RX100", slug: "rx-100", weights: [400], italics: false, category: "sans" },
  { family: "Satoshi", slug: "satoshi", weights: [0,300,400,500,700,900], italics: true, category: "sans" },
  { family: "Segment", slug: "segment", weights: [400], italics: false, category: "display" },
  { family: "Sentient", slug: "sentient", weights: [0,200,300,400,500,700], italics: true, category: "serif" },
  { family: "Sharpie", slug: "sharpie", weights: [0,300,400,700,800,900], italics: false, category: "display" },
  { family: "Stardom", slug: "stardom", weights: [400], italics: false, category: "display" },
  { family: "Striper", slug: "striper", weights: [400], italics: false, category: "display" },
  { family: "Styro", slug: "styro", weights: [0,200,300,400,500,600,700,800,900], italics: false, category: "display" },
  { family: "Supreme", slug: "supreme", weights: [0,100,200,300,400,500,700,800], italics: true, category: "sans" },
  { family: "Switzer", slug: "switzer", weights: [0,100,200,300,400,500,600,700,800,900], italics: true, category: "sans" },
  { family: "Synonym", slug: "synonym", weights: [0,200,300,400,500,600,700], italics: false, category: "sans" },
  { family: "Tabular", slug: "tabular", weights: [0,300,400,500,600,700], italics: true, category: "sans" },
  { family: "Tanker", slug: "tanker", weights: [400], italics: false, category: "sans" },
  { family: "Technor", slug: "technor", weights: [0,200,300,400,500,600,700,900], italics: false, category: "sans" },
  { family: "Telma", slug: "telma", weights: [0,300,400,500,700,900], italics: false, category: "script" },
  { family: "Trench Slab", slug: "trench-slab", weights: [0,300,400,500,600,700], italics: false, category: "slab" },
  { family: "Zina", slug: "zina", weights: [400], italics: false, category: "display" },
  { family: "Zodiak", slug: "zodiak", weights: [0,100,300,400,700,800,900], italics: true, category: "serif" },
];
